ALTER TYPE "AcademicPeriod" RENAME VALUE 'FIRST_TERM' TO 'BIMESTRE_1';
ALTER TYPE "AcademicPeriod" RENAME VALUE 'SECOND_TERM' TO 'BIMESTRE_2';
ALTER TYPE "AcademicPeriod" RENAME VALUE 'THIRD_TERM' TO 'BIMESTRE_3';
ALTER TYPE "AcademicPeriod" ADD VALUE IF NOT EXISTS 'BIMESTRE_4' BEFORE 'FINAL';
