ALTER TYPE "AlertStatus" RENAME VALUE 'OPEN' TO 'PENDIENTE';
ALTER TYPE "AlertStatus" RENAME VALUE 'IN_PROGRESS' TO 'EN_REVISION';
ALTER TYPE "AlertStatus" RENAME VALUE 'RESOLVED' TO 'ATENDIDA';
ALTER TYPE "AlertStatus" RENAME VALUE 'DISMISSED' TO 'DESCARTADA';
