ALTER TYPE "AttendanceStatus" RENAME VALUE 'PRESENT' TO 'PRESENTE';
ALTER TYPE "AttendanceStatus" RENAME VALUE 'ABSENT' TO 'FALTA';
ALTER TYPE "AttendanceStatus" RENAME VALUE 'LATE' TO 'ATRASO';
ALTER TYPE "AttendanceStatus" RENAME VALUE 'JUSTIFIED' TO 'JUSTIFICADO';
